### ISSUE TITLE
No camera data on dashboard when running `.run tracking up`

### ISSUE THREAD

**Issue by yushan111** [cisco-open/DeepVision#49]
## Description

When run the application tracking, there is no camera data shown on dashboard
 
<img width="1720" alt="Screenshot 2023-06-27 at 6 30 27 PM" src="https://github.com/cisco-open/DeepVision/assets/12656939/214100a2-6be9-4bd6-a5a9-9165199206d6">

Also "http://localhost:5002/video?" is always loading (without any data).

More information:

- The application "haidetection" works normally.
-  By using `server2.py`, instead of `server1.py` in the `producer` service of `docker-compose.yml`, it works fine.

It seems `server2.py` is a refactored version of `server.py`, whose application streams code have been well-decoupled. Will we replace the `server.py` with `server2.py` for all the applications? 

## Expected Behavior

Camera data shows the annotated video stream on dashboard.

## Actual Behavior

Camera data is empty.

## Affected Version

Tested on the "main" branch

## Steps to Reproduce

run `.run tracking up`

## Checklist

- [x] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by hmlatapie** [comment]
issue confirmed and resolved.
